title: devML
baseurl: '/'
url: 'https://devml.io'
permalink: pretty
exclude:
  - artwork
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - LICENSE.txt
  - lib/
  - README.md
  - contributors.md
search_enabled: true
aux_links:
  'devML on GitHub':
    - 'https://github.com/gar1t/devML'
